### ISSUE TITLE
Hoc broken with typescript@3.2.1

### ISSUE THREAD

**Issue by belgattitude** [piotrwitek/react-redux-typescript-guide#111]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://issuehunt.io/r/piotrwitek/react-redux-typescript-guide/issues/111)

Got an issue with hoc and typescript 3.2.1, any idea of what's missing

Based on latest master:

https://github.com/piotrwitek/react-redux-typescript-guide/blob/master/playground/src/hoc/with-state.tsx

Tsc will fail with

```
hoc/with-state.tsx:41:18 - error TS2322: Type '{ count: number; onIncrement: () => void; }' is not assignable to type 'IntrinsicAttributes & WrappedProps & { children?: ReactNode; }'.
  Property 'count' does not exist on type 'IntrinsicAttributes & WrappedProps & { children?: ReactNode; }'.
```

Any ideas ?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($50.00)
### Submitted pull Requests
- [#193 Updated Guide and refactored playground project to work with the most recent TypeScript 3.7 and React & Redux type definitions.](https://issuehunt.io/r/piotrwitek/react-redux-typescript-guide/pull/193)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/piotrwitek/react-redux-typescript-guide/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by piotrwitek** [comment]
@belgattitude thanks for report, there was a change with generic object spread, I need to investigate

Related #100 #101

**Comment by belgattitude** [comment]
Thanks a lot... 

I'm trying to figure out as well. If I find something I'll let you know. 

Can be useful too: https://github.com/Microsoft/TypeScript/issues/28748

**Comment by IssuehuntBot** [comment]
@issuehuntfest has funded $20.00 to this issue. [See it on IssueHunt](https://issuehunt.io/repos/76996763/issues/111)

**Comment by JKillian** [comment]
Looks like the TypeScript team thinks this is a bug and is trying to fix it by next release:

![image](https://user-images.githubusercontent.com/1400151/49825344-284bc500-fd52-11e8-9f69-918cfb60f6e5.png)

Unfortunately, might mean it's difficult to fix from this side of things (though who knows, maybe there's a workaround)

**Comment by piotrwitek** [comment]
Thanks for heads-up @JKillian! I'll be tracking that one.

**Comment by WojciechMatuszewski** [comment]
[Explanation and temporary solution](https://github.com/Microsoft/TypeScript/issues/28938#issuecomment-450636046)

**Comment by piotrwitek** [comment]
Another related issue: https://github.com/Microsoft/TypeScript/issues/28884

**Comment by IssuehuntBot** [comment]
@issuehunt has funded $30.00 to this issue.

---
- Submit pull request via [IssueHunt](https://issuehunt.io/repos/76996763/issues/111) to receive this reward.
- Want to contribute? Chip in to this issue via [IssueHunt](https://issuehunt.io/repos/76996763/issues/111).
- Checkout the [IssueHunt Issue Explorer](https://issuehunt.io/issues) to see more funded issues.
- Need help from developers? [Add your repository](https://issuehunt.io/r/new) on IssueHunt to raise funds.

**Comment by zdila** [comment]
I can't adjust types to use Redux `connect`. Is it related?

```typescript
const tx = ...;

export type Translator = typeof tx;

interface InjectedProps {
  t: Translator;
}

export const withTranslator = <BaseProps extends InjectedProps>(
  _BaseComponent: React.ComponentType<BaseProps>,
) => {
  // fix for TypeScript issues: https://github.com/piotrwitek/react-redux-typescript-guide/issues/111
  const BaseComponent = _BaseComponent as React.ComponentType<InjectedProps>;

  type HocProps = Subtract<BaseProps, InjectedProps>;
  type TStateProps = ReturnType<typeof mapStateToProps>;

  class Hoc extends React.Component<HocProps> {
    static displayName = `injectL10n(${BaseComponent.name})`;
    static readonly WrappedComponent = BaseComponent;

    render() {
      const { ...restProps } = this.props;
      return <BaseComponent t={tx} {...restProps} />;
    }
  }

  const mapStateToProps = (state: RootState) => ({
    language: state.l10n.language,
  });
  
  // type error:
  return connect<TStateProps, {}, HocProps, RootState>(mapStateToProps)(Hoc);
};
```


Error:

```
Argument of type 'typeof Hoc' is not assignable to parameter of type 'ComponentType<Matching<{ language: string; } & DispatchProp<AnyAction>, Pick<BaseProps, SetDifference<keyof BaseProps, "t">>>>'.
  Type 'typeof Hoc' is not assignable to type 'ComponentClass<Matching<{ language: string; } & DispatchProp<AnyAction>, Pick<BaseProps, SetDifference<keyof BaseProps, "t">>>, any>'.
    Types of parameters 'props' and 'props' are incompatible.
      Type 'Matching<{ language: string; } & DispatchProp<AnyAction>, Pick<BaseProps, SetDifference<keyof BaseProps, "t">>>' is not assignable to type 'Readonly<Pick<BaseProps, SetDifference<keyof BaseProps, "t">>>'.
        Type 'P extends "dispatch" | "language" ? ({ language: string; } & DispatchProp<AnyAction>)[P] extends Pick<BaseProps, SetDifference<keyof BaseProps, "t">>[P] ? Pick<BaseProps, SetDifference<keyof BaseProps, "t">>[P] : ({ ...; } & DispatchProp<...>)[P] : Pick<...>[P]' is not assignable to type 'BaseProps[P]'.
          Type 'Pick<BaseProps, SetDifference<keyof BaseProps, "t">>[P] | (({ language: string; } & DispatchProp<AnyAction>)[P] extends Pick<BaseProps, SetDifference<keyof BaseProps, "t">>[P] ? Pick<...>[P] : ({ ...; } & DispatchProp<...>)[P])' is not assignable to type 'BaseProps[P]'.
            Type '({ language: string; } & DispatchProp<AnyAction>)[P] extends Pick<BaseProps, SetDifference<keyof BaseProps, "t">>[P] ? Pick<BaseProps, SetDifference<keyof BaseProps, "t">>[P] : ({ ...; } & DispatchProp<...>)[P]' is not assignable to type 'BaseProps[P]'.
              Type '({ language: string; } & DispatchProp<AnyAction>)[P] | Pick<BaseProps, SetDifference<keyof BaseProps, "t">>[P]' is not assignable to type 'BaseProps[P]'.
                Type '({ language: string; } & DispatchProp<AnyAction>)[P]' is not assignable to type 'BaseProps[P]'.
                  Type '{ language: string; } & DispatchProp<AnyAction>' is not assignable to type 'BaseProps'.
                    Type 'SetDifference<keyof BaseProps, "t"> extends "dispatch" | "language" ? ({ language: string; } & DispatchProp<AnyAction>)[("dispatch" & SetDifference<keyof BaseProps, "t">) | ("language" & SetDifference<...>)] extends Pick<...>[("dispatch" & SetDifference<...>) | ("language" & SetDifference<...>)] ? Pick<...>[("dispat...' is not assignable to type 'BaseProps[P]'.
                      Type '(({ language: string; } & DispatchProp<AnyAction>)[("dispatch" & SetDifference<keyof BaseProps, "t">) | ("language" & SetDifference<keyof BaseProps, "t">)] extends Pick<BaseProps, SetDifference<...>>[("dispatch" & SetDifference<...>) | ("language" & SetDifference<...>)] ? Pick<...>[("dispatch" & SetDifference<...>) ...' is not assignable to type 'BaseProps[P]'.
                        Type '({ language: string; } & DispatchProp<AnyAction>)[("dispatch" & SetDifference<keyof BaseProps, "t">) | ("language" & SetDifference<keyof BaseProps, "t">)] extends Pick<BaseProps, SetDifference<...>>[("dispatch" & SetDifference<...>) | ("language" & SetDifference<...>)] ? Pick<...>[("dispatch" & SetDifference<...>) |...' is not assignable to type 'BaseProps[P]'.
                          Type '({ language: string; } & DispatchProp<AnyAction>)[("dispatch" & SetDifference<keyof BaseProps, "t">) | ("language" & SetDifference<keyof BaseProps, "t">)] | Pick<BaseProps, SetDifference<...>>[("dispatch" & SetDifference<...>) | ("language" & SetDifference<...>)]' is not assignable to type 'BaseProps[P]'.
                            Type '({ language: string; }["dispatch" & SetDifference<keyof BaseProps, "t">] & DispatchProp<AnyAction>["dispatch" & SetDifference<keyof BaseProps, "t">]) | ({ language: string; }["language" & SetDifference<...>] & DispatchProp<...>["language" & SetDifference<...>])' is not assignable to type 'BaseProps[P]'.
                              Type '{ language: string; }["dispatch" & SetDifference<keyof BaseProps, "t">] & DispatchProp<AnyAction>["dispatch" & SetDifference<keyof BaseProps, "t">]' is not assignable to type 'BaseProps[P]'.
                                Type 'Pick<BaseProps, SetDifference<keyof BaseProps, "t">>[string] | Pick<BaseProps, SetDifference<keyof BaseProps, "t">>[number] | Pick<BaseProps, SetDifference<keyof BaseProps, "t">>[symbol]' is not assignable to type 'BaseProps[P]'.
                                  Type 'BaseProps[string]' is not assignable to type 'BaseProps[P]'.
                                    Type 'string' is not assignable to type 'P'.
                                      'string' is assignable to the constraint of type 'P', but 'P' could be instantiated with a different subtype of constraint 'string | number | symbol'.
```

Thanks.

**Comment by HQ92** [comment]
I'm having the same issue as zdila. My Hoc using redux connect was working perfectly before I updated my typescript and redux packages. The code hasn't changed at all but I'm receiving these errors across all my Hocs which were built in exactly the same way.

I'm using:
"react": "^16.8.6",
"react-redux": "^7.1.0",
"redux": "^4.0.4",
"typescript": "^3.5.3",

**Comment by piotrwitek** [comment]
@zdila this issue is reproduced without connect, but potentially can be related.

**Comment by piotrwitek** [comment]
For issues with nested HOC using `connect` please use the following issue #5

**Comment by piotrwitek** [comment]
The issue is fixed using:
```ts
  {...(restProps as BaseProps)}
```

Full example:
```ts
import React from 'react';
import { Diff } from 'utility-types';

interface InjectedProps {
  count: number;
  onIncrement: () => void;
}

export const withState = <BaseProps extends InjectedProps>(
  BaseComponent: React.ComponentType<BaseProps>
) => {
  type HocProps = Diff<BaseProps, InjectedProps> & {
    initialCount?: number;
  };
  type HocState = {
    readonly count: number;
  };

  return class Hoc extends React.Component<HocProps, HocState> {
    static displayName = `withState(${BaseComponent.name})`;
    static readonly WrappedComponent = BaseComponent;

    readonly state: HocState = {
      count: Number(this.props.initialCount) || 0,
    };

    handleIncrement = () => {
      this.setState({ count: this.state.count + 1 });
    };

    render() {
      const { ...restProps } = this.props;
      const { count } = this.state;

      return (
        <BaseComponent
          count={count}
          onIncrement={this.handleIncrement}
          {...(restProps as BaseProps)} // <= HERE
        />
      );
    }
  };
};
```

**Comment by piotrwitek** [comment]
@zdila I have added a solution for your issue in #5 and soon it will be added to the guide as a new section
